"use client";

import styles from "../checkout.module.css";
import { cx } from "../../../lib/utils";
import { PAYMENT_METHODS } from "../mock-data";
import Spinner from "../../components/Spinner";

type Props = {
  infoSummaryHtml: string;
  onEditInfo: () => void;
  payMethod: string;
  onSelectPayMethod: (code: string) => void;
  cardToken: string;
  onCardTokenChange: (v: string) => void;
  gpaySuccessUrl: string;
  onGpaySuccessUrlChange: (v: string) => void;
  billingSame: boolean;
  onBillingSameChange: (v: boolean) => void;
  isLoading: boolean;
  total: number | null;
  fmt: (n: number) => string;
  onPlaceOrder: () => void;
  onBack: () => void;
};

export default function PaymentStep({
  infoSummaryHtml,
  onEditInfo,
  payMethod,
  onSelectPayMethod,
  cardToken,
  onCardTokenChange,
  gpaySuccessUrl,
  onGpaySuccessUrlChange,
  billingSame,
  onBillingSameChange,
  isLoading,
  total,
  fmt,
  onPlaceOrder,
  onBack,
}: Props) {
  return (
    <div className={styles.stepPanel}>
      <div className={styles.card}>
        <div className={styles.cardHead}>Payment</div>
        <div className={styles.infoSummary}>
          <div className={styles.infoSumText} dangerouslySetInnerHTML={{ __html: infoSummaryHtml }} />
          <button className={styles.infoSumEdit} onClick={onEditInfo}>
            Edit
          </button>
        </div>

        {/* Method tabs */}
        <div className={styles.pmGrid}>
          {PAYMENT_METHODS.map((m) => (
            <button
              key={m.code}
              className={cx(styles.pmMethod, payMethod === m.code && styles.active)}
              onClick={() => onSelectPayMethod(m.code)}
              title={m.code}
            >
              <span className={styles.pmMethodIcon}>{m.icon}</span>
              <span>{m.label}</span>
              <span className={styles.pmMethodCode}>{m.code}</span>
            </button>
          ))}
        </div>

        {/* card_token panel */}
        {payMethod === "card_token" && (
          <div>
            <div className={styles.fieldRow}>
              <div className={styles.fieldGroup}>
                <label className={styles.fieldLabel}>
                  Card Token <span className={styles.fieldTag}>card_token</span>
                </label>
                <input
                  className={cx(styles.fieldInput, styles.fieldInputMono)}
                  type="text"
                  value={cardToken}
                  onChange={(e) => onCardTokenChange(e.target.value)}
                  placeholder="tok_visa_xxxxxxxxxxxx"
                />
                <span className={styles.fieldHint}>Token generated by your payment provider (Stripe, etc.)</span>
              </div>
            </div>
          </div>
        )}

        {/* google_pay panel */}
        {payMethod === "google_pay" && (
          <div>
            <div className={styles.fieldRow}>
              <div className={styles.fieldGroup}>
                <label className={styles.fieldLabel}>
                  Success URL <span className={styles.fieldTag}>success_url</span>
                </label>
                <input
                  className={styles.fieldInput}
                  type="text"
                  value={gpaySuccessUrl}
                  onChange={(e) => onGpaySuccessUrlChange(e.target.value)}
                  placeholder="https://yourdomain.com/order/success/"
                />
                <span className={styles.fieldHint}>Redirect URL after Google Pay authorization completes.</span>
              </div>
            </div>
            <div className={styles.notReqNote}>
              <svg width="12" height="12" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                <path d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              <code>google_pay</code> is in <code>NOT_REQUIRE_USER_PAYMENT_METHODS</code> — <code>user</code> field is
              optional
            </div>
          </div>
        )}

        {/* Billing */}
        <div className={styles.billingSection}>
          <div className={styles.checkboxRow}>
            <input
              type="checkbox"
              id="billingSame"
              checked={billingSame}
              onChange={(e) => onBillingSameChange(e.target.checked)}
            />
            <label className={styles.checkboxLabel} htmlFor="billingSame">
              Billing address same as shipping{" "}
              <span className={styles.fieldTag}>billing_same_as_shipping_address</span>
            </label>
          </div>
        </div>
      </div>

      <button className={styles.btnPrimary} disabled={isLoading} onClick={onPlaceOrder}>
        {isLoading ? (
          <>
            <Spinner size={16} />
            Processing...
          </>
        ) : (
          <>
            <svg width="16" height="16" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
              <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
            </svg>
            Place Order — {total !== null ? fmt(total) : "..."}
          </>
        )}
      </button>
      <p className={styles.termsNote}>
        By placing your order you agree to our <a href="#">Terms of Service</a> and{" "}
        <a href="#">Privacy Policy</a>.
      </p>
      <button className={styles.btnBack} onClick={onBack}>
        <svg width="14" height="14" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5">
          <path d="M19 12H5M12 19l-7-7 7-7" />
        </svg>
        Return to Shipping
      </button>
    </div>
  );
}
